### PR TITLE
#33: treat `flushTimeoutMSec` as a "problem occuring" more than a "feature" (closes #33)

### LINKED ISSUE #33: treat `flushTimeoutMSec` as a "problem occuring" more than a "feature"
## description
[`flushTimeoutMSec`](https://github.com/buildo/state/blob/master/src/run.js#L209) solves this problem:
- detect a transition as causing a "router diff"
- keep track of the temporary next state but write to the browser/router and wait to sync there before pushing the state update
- expect to be called back by the browser once the new state is pushed to history
- what happens if browser doesn't call back?

99% (or 100%) it means the heuristic of "router diff" is broken, meaning a bug in a library

Currently we are treating it as a feature (clean up pending transition and perform the next one, if any)
We should treat it as a last resort option instead, and warn the user of the libe

## how to reproduce
- {optional: describe steps to reproduce defect}

## specs
Currently we are defaulting it to a small number (`10ms`). We should instead:
- default it to something bigger enough that, while developing, it is clear that something is going terribly wrong if your app relies on it to work properly
  - 5 seconds should do the trick
- add a warning in console when in dev and flush timeout expires

## misc
{optional: other useful info}

### PR DESCRIPTION
**Pull request by giogonzo**
Closes #33

### tests performed
- tested briefly on aliniq
- will assign to someone else on the project for a thorough review tomorrow
- we should do the same on other projects too..

> An example of partial test is a field displaying 4 possible values. If 3 values are tested, with screenshots, and 1 is not, then it should be mentioned here.}

### CODE REVIEW

File: src/run.js [hunk 1]
```diff
@@ -250,10 +253,6 @@ export default stateType => ({
     } else {
       log('browser change: browser initiated');
       state.next(transitionReducer(mergeStateAndBrowserState(state.value, fromRouter)));
-      // push a dummy transition
-      // so that `transitionReducer` can run
-      // will be diffed away if there's nothing else to be done
-      transition({ ___k: Math.random() });
```
Comment (giogonzo) [inline src/run.js:256]: this was now:
- unneeded (`transitionReducer` is run a few lines above)
- potentially dangerous on app boot (if routerDiff fails basically you can't use the app for the first `timeoutMSec` milliseconds)

File: src/run.js [hunk 2]
```diff
@@ -37,6 +37,9 @@ export function createProvideWrapper({
     }
     flushTimeout = setTimeout(() => {
       if (queue.length > 0 && queue[0].time <= Date.now() - flushTimeoutMSec) {
+        if (process.env.NODE_ENV !== 'production') {
+          console.warn('state:flushTimeout', 'flushTimeout expired! We probably were expecting an update from the router that did\'t call us instead :\'('); // eslint-disable-line no-console
```
Comment (FrancescoCioria) [inline src/run.js]: typo: `did\'t` instead of `didn\'t`

**Review by FrancescoCioria — APPROVED** [review]

**Review by FrancescoCioria — APPROVED** [review]
