### PR TITLE
#31: breaking: enforce omitByF(t.Nil.is) also for changes coming from browser (closes #31)

### LINKED ISSUE #31: breaking: enforce omitByF(t.Nil.is) also for changes coming from browser
## description
{describe the defective behavior}

## how to reproduce
- {optional: describe steps to reproduce defect}

## specs
{optional: describe a possible fix for this defect, if not obvious}

## misc
{optional: other useful info}

### PR DESCRIPTION
**Pull request by giogonzo**
Closes #31

## Test Plan

> These results can be screenshots, query results, or even just pointers to unit tests that successfully passed.}

> An example of partial test is a field displaying 4 possible values. If 3 values are tested, with screenshots, and 1 is not, then it should be mentioned here.}

### CODE REVIEW

File: src/run.js [hunk 1]
```diff
@@ -78,23 +80,22 @@ export function createProvideWrapper({
...
-    // log('patch is:', patch);
+    log('state is:', state);
+    log('patch is:', patch);
     const shouldReplace = isTransitionFunction;
-    const newState = stateType(pickBy(
-      transitionReducer(shouldReplace ? { ...patch } : { ...state, ...patch }),
-      x => !t.Nil.is(x)
-    ));
+    const newState = stateType(
+      transitionReducer(shouldReplace ? { ...patch } : { ...state, ...patch })
```
Comment (FrancescoCioria) [inline src/run.js:87]: what about this one?

Comment (giogonzo) [reply src/run.js:87]: Should be already handled by `omitNils` everywhere, right?

Comment (FrancescoCioria) [reply src/run.js:87]: oh right, it's passed as an argument by the other function (I thought it was used before)
👍
